name: reusable release workflow prepare pull request action
description: get commit author; get new branch name; checkout and push new empty branch; git add; git commit; create pull request with inputs.reviewer

inputs:
  githubToken:
    description: github app token
    required: true
  releaseVersion:
    description: new release version
    required: true
  reviewerUsername:
    description: pull-request reviewer username
    required: true
  baseBranchName:
    description: base branch name - release or sync usually
    default: release
    required: false

runs:
  using: composite

  steps:
    - name: Create release branch
      shell: bash
      id: createReleaseBranchStep
      run: |
        set -e

        branch="${{ inputs.baseBranchName }}/${{ inputs.releaseVersion }}"
        git fetch origin
        git switch -c "$branch"
        git push origin "$branch"

        echo "branchName=$branch" >> "$GITHUB_OUTPUT"

    # TODO uncomment
    # - uses: atls/shared/.github/actions/github/pull-request/get-last-author@master
    - uses: atls/shared/.github/actions/github/pull-request/get-last-author@refactor/workflow
      id: lastPrAuthorStep
      with:
        githubToken: ${{ inputs.githubToken }}

    # TODO uncomment
    # - uses: atls/shared/.github/actions/github/commit/create@master
    - uses: atls/shared/.github/actions/github/commit/create@refactor/workflow
      with:
        branchName: ${{ steps.createReleaseBranchStep.outputs.branchName }}
        githubToken: ${{ inputs.githubToken }}
        targetRepository: ${{ github.repository }}

    - name: Add a short delay for stability
      shell: bash
      run: sleep 10s

    # TODO uncomment
    # - uses: atls/shared/.github/actions/github/pull-request/create@master
    - uses: atls/shared/.github/actions/github/pull-request/create@refactor/workflow
      with:
        targetDirectory: .
        githubToken: ${{ inputs.githubToken }}
        lastPrAuthor: ${{ steps.lastPrAuthorStep.outputs.lastPrAuthor }}
        prTitle: 'Bump version to ${{ inputs.releaseVersion }}'
        prBody: 'Automated version bump'
        branchName: ${{ steps.createReleaseBranchStep.outputs.branchName }}
        reviewerUsername: ${{ inputs.reviewerUsername }}
