name: Reusable checks

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node version to run this workflow. Default: 19'
        default: '19'
        required: false
        type: string

jobs:
  checks:
    name: Lint, typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Load .env file
        uses: falti/dotenv-action@v1
        with:
          path: .env

      - name: Install
        run: yarn install

      - name: Lint
        run: yarn checks lint
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: TypeCheck
        run: yarn checks typecheck
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
