name: Sync Android Repositories

env:
  TARGET_TMP_DIR_PATH: tmp/target
  SOURCE_TMP_DIR_PATH: tmp/source

on:
  workflow_call:
    inputs:
      appId:
        type: string
        required: true
      targetRepository:
        type: string
        required: true
      targetOrganization:
        type: string
        required: true
      sourceDirname:
        type: string
      targetDirname:
        type: string
      syncIgnore:
        type: string
        required: true
        description: list of files to exclue, separated by ','
        default: ".git,.idea,LICENSE,"
      replacementExtentions:
        type: string
        required: true
        description: list of extentions to replace, separated by ','
        default: "*.ts,*.sh,*.yaml"
      replacementContents:
        type: string
        required: true
        description: list of contents to replace, separated by ',' and '|' - separate source target content\
        default: "source:content:1|target:conten:1,source-content-1|target-content-1"
    secrets:
      privateKey:
        required: true

jobs:
  run:
    name: Synchronization
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: appTokenStep
        with:
          app-id: ${{ inputs.appId }}
          private-key: ${{ secrets.privateKey }}
          owner: ${{ inputs.targetOrganization }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ${{ env.SOURCE_TMP_DIR_PATH }}
          token: ${{ steps.appTokenStep.outputs.token }}

      - name: Checkout remote repository
        uses: actions/checkout@v4
        with:
          path: ${{ env.TARGET_TMP_DIR_PATH }}
          token: ${{ steps.appTokenStep.outputs.token }}
          repository: ${{inputs.targetRepository}}

      # TODO uncomment
      # - uses: atls/shared/.github/actions/utils/fs/clean-dir@master
      - uses: atls/shared/.github/actions/utils/fs/clean-dir@feat/synchronization-workflow
        with:
          targetDirectory: ${{ env.TARGET_TMP_DIR_PATH }}
          syncIgnore: ${{ inputs.syncIgnore }}

      # TODO uncomment
      # - uses: atls/shared/.github/actions/utils/fs/sync-dirs@master
      - uses: atls/shared/.github/actions/utils/fs/sync-dirs@feat/synchronization-workflow
        with:
          syncIgnore: ${{ inputs.syncIgnore }}
          targetDirectory: ${{ env.TARGET_TMP_DIR_PATH }}
          sourceDirectory: ${{ env.SOURCE_TMP_DIR_PATH }}

        # TODO uncomment
        # - uses: atls/shared/.github/actions/utils/fs/replace-file-content@master
      - uses: atls/shared/.github/actions/utils/fs/replace-file-content@feat/synchronization-workflow
        with:
          syncIgnore: ${{ inputs.syncIgnore }}
          targetDirectory: ${{ env.TARGET_TMP_DIR_PATH }}
          replacementExtentions: ${{ inputs.replacementExtentions }}
          replacementContents: ${{ inputs.replacementContents }}

        # TODO uncomment
        # - uses: atls/shared/.github/actions/utils/fs/rename-dirs@master
      - uses: atls/shared/.github/actions/utils/fs/rename-dirs@feat/synchronization-workflow
        if: ${{ inputs.sourceDirname != '' && inputs.targetDirname != '' }}
        with:
          targetDirectory: ${{ env.TARGET_TMP_DIR_PATH }}
          sourceDirname: ${{ inputs.sourceDirname }}
          targetDirname: ${{ inputs.targetDirname }}

      # TODO why not delete tmp?
      # TODO uncomment
      # - uses: atls/shared/.github/actions/utils/fs/sync-dirs@master
      - uses: atls/shared/.github/actions/utils/fs/sync-dirs@feat/synchronization-workflow
        with:
          targetDirectory: ${{ env.TARGET_TMP_DIR_PATH }}
          sourceDirectory: .

        # TODO uncomment
        # - uses: atls/shared/.github/actions/github/pull-request/get-last-author@master
      - uses: atls/shared/.github/actions/github/pull-request/get-last-author@feat/synchronization-workflow
        id: lastPrAuthorStep
        with:
          githubToken: ${{ steps.appTokenStep.outputs.token }}

        # TODO uncomment
        # - uses: atls/shared/.github/actions/github/utils/get-new-branch-name@master
      - uses: atls/shared/.github/actions/github/utils/get-new-branch-name@feat/synchronization-workflow
        id: newBranchNameStep

        # TODO uncomment
        # - uses: atls/shared/.github/actions/github/checkout/new-branch@master
      - uses: atls/shared/.github/actions/github/checkout/new-branch@feat/synchronization-workflow
        with:
          branchName: ${{ steps.newBranchNameStep.outputs.branchName }}

        # TODO move to actions; excludeTmp - optional flag
      - name: git add
        run: |
          git add --all -- . ':!tmp/'

          # TODO remove if not needed
      #   # TODO uncomment
      #   # - uses: atls/shared/.github/actions/github/push/create@master
      # - uses: atls/shared/.github/actions/github/push/create@feat/synchronization-workflow
      #   with:
      #     branchName: ${{ steps.newBranchNameStep.outputs.branchName }}
      #     githubToken: ${{ steps.appTokenStep.outputs.token }}
      # TODO uncomment
      # - uses: atls/shared/.github/actions/github/commit/create@master
      - uses: atls/shared/.github/actions/github/commit/create@feat/synchronization-workflow
        with:
          branchName: ${{ steps.newBranchNameStep.outputs.branchName }}
          githubToken: ${{ steps.appTokenStep.outputs.token }}
          targetRepository: ${{ env.TARGET_REPO }}

        # TODO uncomment
        # - uses: atls/shared/.github/actions/github/pull-request/create@master
      - uses: atls/shared/.github/actions/github/pull-request/create@feat/synchronization-workflow
        with:
          githubToken: ${{ steps.appTokenStep.outputs.token }}
          lastPrAuthor: ${{ steps.lastPrAuthorStep.outputs.lastPrAuthor }}
          branchName: ${{ steps.newBranchNameStep.outputs.branchName }}
