name: Reusable tools

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node version to run this workflow. Default: 18.19 as it is in action cache'
        default: '18.19'
        required: false
        type: string
      version:
        description: 'Tools yarn version'
        type: string
        required: true
    secrets:
      patToken:
        required: true

jobs:
  update:
    name: Update Tools
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install
        run: yarn install

      - name: Update
        run: yarn set version from tag ${{ inputs.version }}
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'feat: update tools'
          title: 'feat: update tools'
          branch-suffix: random
          delete-branch: true
          body: |
            Update tools to ${{ inputs.version }}.
