name: Reusable JS/TS version bump & create PR

on:
  workflow_call:
    inputs:
      appId:
        description: 'github app id'
        required: true
        type: string
      node-version:
        description: 'Node version to run this workflow. Default: 19 as it is in action cache'
        default: '22'
        required: false
        type: string
      workingDirectory:
        description: Working direction for action
        default: ./
        type: string
        required: false
      reviewerUsername:
        description: Working direction for action
        default: ./
        type: string
        required: false
      exclude:
        description: Exclude to bump
        default: '.'
        type: string
        required: false
      checkChanges:
        description: Should run 'yarn --since'?
        required: false
        type: string
        default: 'true'
      private:
        description: Should apply only to private?
        required: false
        type: string
        default: 'false'
    secrets:
      appSecret:
        required: true

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ inputs.appId }}
          private-key: ${{ inputs.appSecret }}

      - name: Start JS action
        id: start
        uses: atls/shared/.github/actions/js/prepare-js@master
        with:
          appId: ${{ inputs.appId }}
          appSecret: ${{ secrets.appSecret }}

      - name: Find last tag commit
        id: lastTagCommit
        uses: aths/shared/.github/actions/git/find-last-tag-commit@master

      - name: Bump version
        uses: atls/shared/.github/actions/js/bump-version-js@master
        with:
          checkChanges: ${{ inputs.checkChanges }}
          private: ${{ inputs.private }}
          token: ${{ steps.app-token.outputs.token }}
          baseCommit: ${{ steps.lastTagCommit.outputs.lastTagCommit }}
          exclude: ${{ inputs.exclude }}

      - name: Generate changelog
        uses: atls/shared/.github/actions/js/generate-changelog@master
        with:
          githubToken: ${{ steps.app-token.outputs.token }}
          baseCommit: ${{ steps.lastTagCommit.outputs.lastTagCommit }}
          exclude: ${{ inputs.exclude }}

      - uses: codfish/semantic-release-action@v3
        id: semanticReleaseStep
        env:
          GH_TOKEN: ${{ inputs.githubToken || steps.app-token.outputs.token || secrets.GITHUB_TOKEN }}

      - name: Check release published
        shell: bash
        run: |
          if [ "${NEW_RELEASE_PUBLISHED}" != "true" ]; then
            echo "New release not published, exit"
            exit 1
          fi

      - name: Debug git diff
        id: git_diff
        run: |
          git diff --quiet || echo "has_changes=true" >> "$GITHUB_OUTPUT"

      - uses: rees46/workflow/.github/actions/release/prepare-pr@master
        if: steps.git_diff.outputs.has_changes == 'true'
        with:
          reviewerUsername: ${{ inputs.reviewerUsername }}
          githubToken: ${{ steps.app-token.outputs.token }}
          releaseVersion: ${{ steps.semanticReleaseStep.outputs.release-version }}
